### ISSUE TITLE
More than 5 fragments in a Navigation Drawer

### ISSUE THREAD

**Issue by SushiFu** [ncapdevi/FragNav#63] opened 2017-04-28 03:58 UTC
This library could be very useful to manage Navigation Drawer, but there is a limitation of 5 "tab fragments".
Could you provide a way to override this please ?

**Comment by ncapdevi** [comment] 2017-04-30 18:32
Yeah, I realized this was going to be an issue at some point. The original library was designed with the bottom tab bar in mind, but that's really just overly-limiting. I will make an update soon.

**Comment by b2cbd** [comment] 2017-06-24 14:11
@ncapdevi  Please add more than "5 fragments"  feature.

**Comment by ncapdevi** [comment] 2017-07-07 17:51
@b2cbd  I'm looking to get to it at some point, but a PR would really get things a lot further. Some historical context to why this isn't available yet is that this library was originally intended to be used with [Material Design's Bottom Navigation](https://material.io/guidelines/components/bottom-navigation.html) which tops out at 5.  It's in the cards, but takes quite a bit of design decisions, hence the `help wanted` tag on this issue

**Comment by Thomas-Vos** [comment] 2017-07-09 17:47
@ncapdevi See pull request #80.

**Comment by ncapdevi** [comment] 2017-07-19 16:52
Will test before the end of the week, but looks right to me. In my head it was going to be more complicated than that, so thanks for the PR.  If all is well, will merge in and push an update before the weekend and close this issue.

**Comment by SushiFu** [comment] 2017-07-21 00:58
For the moment I've made a quick fix too.
But I'm working on a "non-limited" solution: In the Builder when you declare your list of root fragments, you could also passed an enum which follow your list (only condition number of elements in enum class need to match with list size) and after that you could use ordinal on each enum element. So after switching tab will look like this: `nav.switchTab(MyNavEnum.HOME);`

**Comment by ncapdevi** [comment] 2017-08-05 22:07
#80 Merged into version 2.1.0

**Comment by ncapdevi** [comment] 2017-08-05 22:07
@SushiFu I'm interested in coming back in exploring this idea in the future.

**Closed as completed by ncapdevi** 2017-08-05 22:07 UTC
Labels: enhancement, help wanted
