### ISSUE TITLE
Fragments re-creating each time I change screen orientation

### ISSUE THREAD

**Issue by FilipeOS** [ncapdevi/FragNav#24] opened 2016-08-20 22:22 UTC
Any solution for this please? Basically the fragments are re-creating each time I do that, adding the new fragment to the bottom of the screen/fragment.

**Comment by cboisen** [comment] 2016-08-21 16:29
Duplicate of [this issue](https://github.com/ncapdevi/FragNav/issues/11).

**Closed as completed** 2016-08-21 16:31 UTC
