### ISSUE TITLE
pop fragment with transitionOption not working

### ISSUE THREAD

**Issue by rayhanuddin55** [ncapdevi/FragNav#83] opened 2017-07-25 09:01 UTC
pop fragment with transitionOption worked fine in version 2.0.1. But in the current version(2.0.2) push work with transition option but pop not.

**Comment by sbfss** [comment] 2017-10-03 09:25
Any update?

**Comment by ncapdevi** [comment] 2017-10-03 16:21
Apologies. I haven't actually had a chance to look into this yet. Will try to do so in the coming days.

**Comment by porkyhead** [comment] 2018-01-08 19:28
I also having trouble getting the correct behavior when using tranistionOption. I am not able to get the return transition working with a shared element. Any suggestions or progress on this issue?

**Comment by asshyy-ktz** [comment] 2018-02-13 15:35
its not a bug, it seems the interface containing pushFragment() & popFragment() having only pushFragment() method.
only update the interface named "FragmentNavigation" in BaseFragement class by declaring function named " void popFragment(); "
then just implement popFragment() method in the class in which you implement this interface.

after updating sample code it look like:

public interface FragmentNavigation {
        void pushFragment(Fragment fragment);
        void popFragment();
    }

    @Override
    public void popFragment() {
        if (mNavController != null) {
            mNavController.popFragment();
        }
    }

**Comment by ncapdevi** [comment] 2018-02-13 15:48
@ismaielsharif Your comment isn't relevant for the transactionOptions which is the original issue, and your provided solution is only necessary if the fragments themselves need to initiate a pop, which is rarely the case as it's often handled by the Activity and back navigation as can be seen in `BottomTabsActivity.kt`


```
   override fun onBackPressed() {
        if (fragNavController?.popFragment()?.not() == true) {
            super.onBackPressed()
        }
    }
```

This issue is for discussion a problem with transitionOptions, not general pop navigation

**Comment by ncapdevi** [comment] 2018-02-13 15:49
I believe this issue has been corrected, but if it hasn't please comment and I'll reopen

**Comment by sebastianmarschall** [comment] 2018-03-06 07:39
the issue still persists in 2.4.0
please reopen @ncapdevi

**Comment by diogojg** [comment] 2018-03-22 02:59
Yes, I have the same issue. Any workaround?

**Comment by diogojg** [comment] 2018-03-22 11:04
@rayhanuddin55 I can't even get it to work on back press on the version you mentioned '2.0.1'.
The shared elements transition works well on pushing a new fragment, but when I do popFragment() only the typical Fade animation is performed, and no shared elements in the transition.

**Comment by porkyhead** [comment] 2018-03-22 12:34
Same issue here as described by @diogojg 

@rayhanuddin55 or @ncapdevi Will you reopen this issue?

**Comment by chnouman** [comment] 2018-06-22 10:41
same issue please reopen it.

**Comment by fr-hyun** [comment] 2018-07-20 01:29
Is there someone or project to fix this issue? 
I want to help to solve this

**Comment by ugurcany** [comment] 2018-10-10 14:24
+1

**Comment by ncapdevi** [comment] 2018-12-26 16:21
Should be fixed in 3.1.0 #187

**Closed as completed by ncapdevi** 2018-12-26 16:21 UTC
Labels: bug

**Comment by javad-vovin** [comment] 2019-01-06 12:58
I still have this issue, after updating to 3.1.0

**Comment by porkyhead** [comment] 2019-02-22 08:26
Still cannot get it to work with 3.1.0. 

@ncapdevi Do you have a sample showing how it should be done in 3.1.0?

**Comment by mecoFarid** [comment] 2019-06-16 12:45
Using the latest `3.2.0` version popAnimation is still not working.

**Comment by khunzohn** [comment] 2020-03-12 05:35
Yet not working for 3.3.0
